-- AuditAction: nouvelles actions métier
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DIAGNOSTIC_ENTER';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REBOOT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GENERATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PUSH';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOWNLOAD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'UPLOAD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MESSAGE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONFIRM';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DIAGNOSE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REPLY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CONNECT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DISCONNECT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPORT';

-- VoucherBatchStatus
ALTER TYPE "VoucherBatchStatus" ADD VALUE IF NOT EXISTS 'PARTIAL_SUCCESS';

-- EventOutcome + AuditLog.outcome
CREATE TYPE "EventOutcome" AS ENUM ('SUCCESS', 'WARNING', 'PARTIAL_SUCCESS', 'FAILED');
ALTER TABLE "AuditLog" ADD COLUMN "outcome" "EventOutcome" NOT NULL DEFAULT 'SUCCESS';
CREATE INDEX "AuditLog_outcome_idx" ON "AuditLog"("outcome");

-- AuditLog.userId -> User
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
