export const ErrorCode = {
  // ── Auth ──
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REUSE: 'AUTH_TOKEN_REUSE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',
  AUTH_PASSWORD_REQUIRED: 'AUTH_PASSWORD_REQUIRED',
  AUTH_EMAIL_UNVERIFIED: 'AUTH_EMAIL_UNVERIFIED',
  AUTH_EMAIL_REQUIRED: 'AUTH_EMAIL_REQUIRED',
  AUTH_NONCE_INVALID: 'AUTH_NONCE_INVALID',
  AUTH_UNSUPPORTED_METHOD: 'AUTH_UNSUPPORTED_METHOD',
  AUTH_GOOGLE_INVALID: 'AUTH_GOOGLE_INVALID',
  AUTH_GOOGLE_NOT_CONFIGURED: 'AUTH_GOOGLE_NOT_CONFIGURED',
  AUTH_GOOGLE_ALREADY_LINKED: 'AUTH_GOOGLE_ALREADY_LINKED',
  AUTH_GOOGLE_WRONG_ACCOUNT: 'AUTH_GOOGLE_WRONG_ACCOUNT',
  AUTH_APPLE_INVALID: 'AUTH_APPLE_INVALID',
  AUTH_APPLE_NOT_CONFIGURED: 'AUTH_APPLE_NOT_CONFIGURED',

  // ── Tenant / Admin ──
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  TENANT_CONTEXT_MISMATCH: 'TENANT_CONTEXT_MISMATCH',
  ADMIN_SELF_SUSPEND: 'ADMIN_SELF_SUSPEND',
  ADMIN_SELF_MODIFY: 'ADMIN_SELF_MODIFY',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_ADMIN: 'USER_ALREADY_ADMIN',
  USER_DELETED: 'USER_DELETED',
  USER_LIMIT_REACHED: 'USER_LIMIT_REACHED',

  // ── Subscriptions / Invoices ──
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  SUBSCRIPTION_TIER_INSUFFICIENT: 'SUBSCRIPTION_TIER_INSUFFICIENT',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_NOT_PENDING: 'INVOICE_NOT_PENDING',
  INVOICE_CONCURRENT: 'INVOICE_CONCURRENT',
  INVOICE_ALREADY_PROCESSED: 'INVOICE_ALREADY_PROCESSED',
  INVOICE_ID_REQUIRED: 'INVOICE_ID_REQUIRED',

  // ── Tiers ──
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  TIER_ARCHIVED: 'TIER_ARCHIVED',
  TIER_HAS_SUBSCRIBERS: 'TIER_HAS_SUBSCRIBERS',
  TIER_ALREADY_EXISTS: 'TIER_ALREADY_EXISTS',

  // ── Routers ──
  ROUTER_NOT_FOUND: 'ROUTER_NOT_FOUND',
  ROUTER_DUPLICATE_IDENTITY: 'ROUTER_DUPLICATE_IDENTITY',
  ROUTER_IDENTITY_MISMATCH: 'ROUTER_IDENTITY_MISMATCH',
  ROUTER_IDENTITY_REQUIRED: 'ROUTER_IDENTITY_REQUIRED',
  ROUTER_REMOTE_FORBIDDEN: 'ROUTER_REMOTE_FORBIDDEN',
  ROUTER_LIMIT_REACHED: 'ROUTER_LIMIT_REACHED',
  ROUTER_UNREACHABLE: 'ROUTER_UNREACHABLE',
  ROUTER_REBOOT_FAILED: 'ROUTER_REBOOT_FAILED',
  ROUTER_PROVISION_FAILED: 'ROUTER_PROVISION_FAILED',
  ROUTER_CREDS_MISSING: 'ROUTER_CREDS_MISSING',
  ROUTER_CREDS_INVALID: 'ROUTER_CREDS_INVALID',
  ROUTER_COMMAND_REFUSED: 'ROUTER_COMMAND_REFUSED',

  // ── Remote access / WireGuard ──
  WG_TUNNEL_DOWN: 'WG_TUNNEL_DOWN',
  WG_PEER_REMOVAL_FAILED: 'WG_PEER_REMOVAL_FAILED',
  REMOTE_ACCESS_DISABLED: 'REMOTE_ACCESS_DISABLED',
  REMOTE_ACCESS_ALREADY_ACTIVE: 'REMOTE_ACCESS_ALREADY_ACTIVE',
  REMOTE_ACCESS_NOT_FOUND: 'REMOTE_ACCESS_NOT_FOUND',
  TUNNEL_NOT_PROVISIONED: 'TUNNEL_NOT_PROVISIONED',

  // ── Vouchers ──
  VOUCHER_LIMIT_REACHED: 'VOUCHER_LIMIT_REACHED',
  VOUCHER_PUSH_TIMEOUT: 'VOUCHER_PUSH_TIMEOUT',
  VOUCHER_PUSH_FAILED: 'VOUCHER_PUSH_FAILED',
  VOUCHER_REVOKE_ROUTER_UNREACHABLE: 'VOUCHER_REVOKE_ROUTER_UNREACHABLE',
  VOUCHER_DELETE_ROUTER_UNREACHABLE: 'VOUCHER_DELETE_ROUTER_UNREACHABLE',
  VOUCHER_NOT_FOUND: 'VOUCHER_NOT_FOUND',
  VOUCHER_ALREADY_REVOKED: 'VOUCHER_ALREADY_REVOKED',
  VOUCHER_ACTIVE_PROTECTED: 'VOUCHER_ACTIVE_PROTECTED',
  BATCH_NOT_FOUND: 'BATCH_NOT_FOUND',

  // ── Plans ──
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',

  // ── Hotspot ──
  HOTSPOT_INVALID_NETWORK: 'HOTSPOT_INVALID_NETWORK',

  // ── Sessions ──
  SESSION_DISCONNECT_FAILED: 'SESSION_DISCONNECT_FAILED',

  // ── Payments ──
  PAYMENT_PROOF_MISSING: 'PAYMENT_PROOF_MISSING',
  PAYMENT_VALIDATION_FAILED: 'PAYMENT_VALIDATION_FAILED',
  PAYMENT_METHOD_INVALID: 'PAYMENT_METHOD_INVALID',
  PROOF_NOT_FOUND: 'PROOF_NOT_FOUND',
  PROOF_FILE_NOT_FOUND: 'PROOF_FILE_NOT_FOUND',

  // ── Files ──
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TYPE_UNSUPPORTED: 'FILE_TYPE_UNSUPPORTED',
  FILE_INVALID: 'FILE_INVALID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // ── PDF / Vault ──
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',
  VAULT_UPLOAD_FAILED: 'VAULT_UPLOAD_FAILED',
  VAULT_PDF_NOT_FOUND: 'VAULT_PDF_NOT_FOUND',

  // ── Support ──
  SUPPORT_TICKET_NOT_FOUND: 'SUPPORT_TICKET_NOT_FOUND',
  SUPPORT_TICKET_CLOSED: 'SUPPORT_TICKET_CLOSED',

  // ── Notifications ──
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // ── Analytics ──
  ANALYTICS_DATE_REQUIRED: 'ANALYTICS_DATE_REQUIRED',

  // ── Audit ──
  AUDIT_WRITE_FAILED: 'AUDIT_WRITE_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
