export const COUNTRIES = [
  { code: 'SN', name: 'Sénégal', flag: '🇸🇳', lang: 'fr' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', lang: 'fr' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', lang: 'fr' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', lang: 'fr' },
  { code: 'GN', name: 'Guinée', flag: '🇬🇳', lang: 'fr' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', lang: 'fr' },
  { code: 'TD', name: 'Tchad', flag: '🇹🇩', lang: 'fr' },
  { code: 'CM', name: 'Cameroun', flag: '🇨🇲', lang: 'fr' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', lang: 'fr' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', lang: 'fr' },
  { code: 'CD', name: 'RD Congo', flag: '🇨🇩', lang: 'fr' },
  { code: 'BJ', name: 'Bénin', flag: '🇧🇯', lang: 'fr' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', lang: 'fr' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', lang: 'fr' },
  { code: 'FR', name: 'France', flag: '🇫🇷', lang: 'fr' },
  { code: 'BE', name: 'Belgique', flag: '🇧🇪', lang: 'fr' },
  { code: 'CH', name: 'Suisse', flag: '🇨🇭', lang: 'fr' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', lang: 'fr' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', lang: 'en' },
  { code: 'US', name: 'United States', flag: '🇺🇸', lang: 'en' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', lang: 'en' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', lang: 'en' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', lang: 'en' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', lang: 'en' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', lang: 'en' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', lang: 'en' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', lang: 'en' },
] as const;

export type Country = typeof COUNTRIES[number];
