"""
Onboarding worker: finalisation state machine (post-bootstrap).

Bootstrap (Steps 1-5) is done by the router itself executing a script
generated by POST /routers/onboard and applied by the user.  Once the router
calls POST /routers/{id}/register-pubkey, the state is WG_READY and this
worker takes over for finalisation only.

State machine (VPS-side):
  WG_READY → (wait VPS handshake) → TUNNEL_UP → (disable LAN API) →
  (rotate password) → LOCKED → DONE
"""
import asyncio
import os
import secrets
import uuid

from models import (
    RouterState,
    get_router,
    update_router_state,
    update_router_admin_password,
    log_step,
)
import routeros_api
from crypto import decrypt_secret, encrypt_secret

SIMULATE_SUCCESS = os.getenv("SIMULATE_SUCCESS", "").lower() in ("1", "true", "yes")
_SIM = "[SIMULATION MODE]"


def decrypt_password(encrypted: str) -> str:
    return decrypt_secret(encrypted)


def encrypt_password(plain: str) -> str:
    return encrypt_secret(plain)


async def onboarding_worker(router_id: str, backend_wg_pubkey: str):
    """
    Finalisation worker.  Expects router to already be in WG_READY state
    (pubkey registered, WG peer added on VPS side).
    """
    from quarantine import on_job_complete

    router = get_router(router_id)
    if not router:
        print(f"Router {router_id} not found")
        return

    ip = router.ip
    username = router.username
    job_id = f"onboard-{router_id}-{uuid.uuid4().hex[:8]}"

    try:
        # ==================== STEP 6: Wait for Tunnel Handshake (VPS-side) ====================
        if router.state == RouterState.WG_READY:
            log_step(router_id, "wait_tunnel_handshake", "start",
                     "Waiting for router to establish WireGuard tunnel to VPS")
            try:
                if SIMULATE_SUCCESS:
                    log_step(router_id, "wait_tunnel_handshake", "info", f"{_SIM} skipped")
                    await asyncio.sleep(0.1)
                else:
                    await routeros_api.wait_tunnel_handshake_vps_side(
                        router_pubkey=router.wg_pubkey,
                        timeout_sec=120,
                    )
                log_step(router_id, "wait_tunnel_handshake", "success")
                update_router_state(router_id, RouterState.TUNNEL_UP)
            except Exception as e:
                log_step(router_id, "wait_tunnel_handshake", "error", str(e))
                update_router_state(router_id, RouterState.ERROR,
                                    error=f"Tunnel handshake failed: {e}")
                await on_job_complete(job_id, "failed", router_id)
                return

        # Reload
        router = get_router(router_id)
        if router.state == RouterState.ERROR:
            return

        # All remaining steps use the WireGuard IP — LAN IP is never used from here.
        wg_ip_host = router.wg_ip.split("/")[0] if router.wg_ip else None
        if not wg_ip_host:
            update_router_state(router_id, RouterState.ERROR, error="No WG IP assigned")
            await on_job_complete(job_id, "failed", router_id)
            return

        log_step(router_id, "finalizing", "info",
                 f"FINALISING via WireGuard tunnel ({wg_ip_host})")
        print(f"FINALISING via WireGuard API connection ({wg_ip_host})")

        password = decrypt_password(router.password_encrypted)

        # ==================== STEP 7: Disable API on LAN ====================
        if router.state == RouterState.TUNNEL_UP:
            log_step(router_id, "disable_api_on_lan", "start")
            try:
                if SIMULATE_SUCCESS:
                    log_step(router_id, "disable_api_on_lan", "info",
                             f"{_SIM} skipped irreversible step")
                else:
                    await routeros_api.disable_api_on_lan(
                        wg_ip_host, username, password, api_port=8728
                    )
                log_step(router_id, "disable_api_on_lan", "success")
            except Exception as e:
                # Non-fatal: hardening step — tunnel is up, continue to DONE
                log_step(router_id, "disable_api_on_lan", "warning",
                         f"Skipped (non-fatal): {e}")

        # ==================== STEP 8: Rotate Admin Password ====================
        if router.state == RouterState.TUNNEL_UP:
            log_step(router_id, "rotate_admin_password", "start")
            try:
                if SIMULATE_SUCCESS:
                    log_step(router_id, "rotate_admin_password", "info",
                             f"{_SIM} skipped irreversible step")
                    update_router_admin_password(
                        router_id, encrypt_password("SIMULATED_PASSWORD")
                    )
                else:
                    new_pass = secrets.token_urlsafe(16)
                    await routeros_api.rotate_admin_password(
                        wg_ip_host, username, password,
                        new_password=new_pass, admin_username="admin"
                    )
                    update_router_admin_password(router_id, encrypt_password(new_pass))
                log_step(router_id, "rotate_admin_password", "success")
                update_router_state(router_id, RouterState.LOCKED)
            except Exception as e:
                # Non-fatal: password rotation is hardening — tunnel is up, continue to DONE
                log_step(router_id, "rotate_admin_password", "warning",
                         f"Skipped (non-fatal): {e}")

        # ==================== FINAL ====================
        log_step(router_id, "onboarding", "success")
        update_router_state(router_id, RouterState.DONE)
        print(f"✓ Router {router_id} ({ip}) onboarded successfully")
        await on_job_complete(job_id, "success", router_id)

    except Exception as e:
        log_step(router_id, "onboarding", "error", str(e))
        update_router_state(router_id, RouterState.ERROR, error=f"Unexpected error: {e}")
        print(f"✗ Router {router_id} ({ip}) failed: {e}")
        await on_job_complete(job_id, "failed", router_id)


async def spawn_onboarding_task(
    router_id: str, backend_wg_pubkey: str
) -> asyncio.Task:
    return asyncio.create_task(onboarding_worker(router_id, backend_wg_pubkey))


async def spawn_multiple_tasks(router_ids: list, backend_wg_pubkey: str) -> list:
    return [await spawn_onboarding_task(rid, backend_wg_pubkey) for rid in router_ids]
